# -*- coding: utf-8 -*-

# DO NOT EDIT THIS FILE!
# This file has been autogenerated by dephell <3
# https://github.com/dephell/dephell

try:
    from setuptools import setup
except ImportError:
    from distutils.core import setup

import os.path

readme = ""
here = os.path.abspath(os.path.dirname(__file__))
readme_path = os.path.join(here, "README.md")
if os.path.exists(readme_path):
    with open(readme_path, "rb") as stream:
        readme = stream.read().decode("utf8")

setup(
    long_description=readme,
    name="pcaddemo",
    version="0.1.0",
    description="pcad demo",
    python_requires="<4,>=3.6",
    author="Martin Lindvall",
    author_email="martin.lindvall@sectra.com",
    entry_points={"console_scripts": ["dephell = dephell.cli:entrypoint"]},
    packages=["pcaddemo"],
    package_data={},
    install_requires=["flask>=1.0", "minilog>=1.2", "requests>=2.22", "shapely>=1.6"],
)
